import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';

// Execute the production Postgres functions. Auth schema substitutes Supabase's host-owned schema.
const pg = new PGlite();
await pg.exec(`create role anon; create role authenticated; create role service_role;
create schema auth; create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql as $$ select null::uuid $$;`);
const schema=(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8')).replace('create extension if not exists pgcrypto;','');
await pg.exec(schema);
async function fixture(total=100,quota=50){const u=randomUUID(),c=randomUUID();await pg.query('insert into auth.users(id,email) values($1,$2)',[u,`${u}@example.com`]);await pg.query("insert into classes(id,name,total,default_quota,image_cost,video_cost,expires_at) values($1,'test',$2,$3,5,20,now()+interval '1 day')",[c,total,quota]);await pg.query('select invite_students($1,$2::text[])',[c,[`${u}@example.com`]]);await pg.query('select claim_memberships($1,$2,$3)',[u,`${u}@example.com`,'Test']);const m=(await pg.query('select * from class_members where class_id=$1',[c])).rows[0];return {u,c,m};}
const reserve=(f,id,kind='image')=>pg.query('select reserve_job($1,$2,$3,$4) result',[f.u,f.c,id,kind]);
const settle=(id,success)=>pg.query('select settle_job($1,$2)',[id,success]);

test('duplicate request IDs and repeated settlement never charge twice',async()=>{const f=await fixture(),id=randomUUID();assert.equal((await reserve(f,id)).rows[0].result.existing,false);assert.equal((await reserve(f,id)).rows[0].result.existing,true);assert.equal((await pg.query('select reserved from class_members where id=$1',[f.m.id])).rows[0].reserved,5);await settle(id,true);await settle(id,true);await settle(id,false);const m=(await pg.query('select used,reserved from class_members where id=$1',[f.m.id])).rows[0];assert.deepEqual(m,{used:5,reserved:0});assert.equal((await pg.query('select count(*)::int n from credit_transactions where job_id=$1',[id])).rows[0].n,2);});
test('concurrent tabs cannot create a second active task, failure refunds once',async()=>{const f=await fixture(),id=randomUUID();await reserve(f,id,'video');await assert.rejects(()=>reserve(f,randomUUID()),/未完成任務/);await settle(id,false);await settle(id,false);assert.deepEqual((await pg.query('select used,reserved from class_members where id=$1',[f.m.id])).rows[0],{used:0,reserved:0});await reserve(f,randomUUID());});
test('personal quota blocks overspending and rolls back the whole reservation',async()=>{const f=await fixture(100,5);const id=randomUUID();await reserve(f,id);await settle(id,true);await assert.rejects(()=>reserve(f,randomUUID()),/不足/);assert.equal((await pg.query('select count(*)::int n from generation_jobs where class_id=$1',[f.c])).rows[0].n,1);assert.deepEqual((await pg.query('select used,reserved from classes where id=$1',[f.c])).rows[0],{used:5,reserved:0});});
test('all allocations are guaranteed, extra students and quota raises cannot exceed the pool',async()=>{const f=await fixture(60,50);await assert.rejects(()=>pg.query('select invite_students($1,$2::text[])',[f.c,['other@example.com']]),/未分配點數不足/);await assert.rejects(()=>pg.query('select set_quota($1,$2,$3)',[f.c,f.m.id,61]),/未分配點數不足/);await pg.query('select set_quota($1,$2,$3)',[f.c,f.m.id,60]);assert.equal((await pg.query('select allocated from classes where id=$1',[f.c])).rows[0].allocated,60);});
test('quota cannot be reduced beneath a reservation; paused and expired classes refuse jobs',async()=>{const f=await fixture(),id=randomUUID();await reserve(f,id,'video');await assert.rejects(()=>pg.query('select set_quota($1,$2,$3)',[f.c,f.m.id,10]),/額度不可低於/);await settle(id,false);await pg.query('update classes set active=false where id=$1',[f.c]);await assert.rejects(()=>reserve(f,randomUUID()),/暫停或到期/);await pg.query("update classes set active=true,expires_at=now()-interval '1 day' where id=$1",[f.c]);await assert.rejects(()=>reserve(f,randomUUID()),/暫停或到期/);});
test('student role cannot mutate quotas, roles or invoke billing functions',async()=>{const f=await fixture();await pg.exec('set role authenticated');try{await assert.rejects(()=>pg.query('update profiles set role=$1 where id=$2',['admin',f.u]),/permission denied/);await assert.rejects(()=>reserve(f,randomUUID()),/permission denied/);await assert.rejects(()=>pg.query('update class_members set quota=99999 where id=$1',[f.m.id]),/permission denied/);}finally{await pg.exec('reset role');}});
test('cross-class simultaneous requests share the same account-wide active limit',async()=>{const f=await fixture();const c=randomUUID();await pg.query("insert into classes(id,name,total,default_quota,image_cost,video_cost,expires_at) values($1,'second',100,50,5,20,now()+interval '1 day')",[c]);await pg.query('select invite_students($1,$2::text[])',[c,[`${f.u}@example.com`]]);await pg.query('select claim_memberships($1,$2,$3)',[f.u,`${f.u}@example.com`,'Test']);const results=await Promise.allSettled([reserve(f,randomUUID()),reserve({...f,c},randomUUID())]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);});
test.after(async()=>{await pg.close();});
