import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUpRight, Bell, BookOpen, Check, ChevronDown, ChevronRight, CircleHelp, Coins, Download, Film, GraduationCap, History, ImagePlus, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Search, Settings2, ShieldCheck, Sparkles, Upload, Users, WandSparkles, X, LoaderCircle, Mail, CircleAlert, RotateCcw } from 'lucide-react';
import type { Classroom, Dashboard, Job, Member } from './types';
import { api, supabase } from './api';
import { loadDemo, demoData } from './demo';

type View = 'studio' | 'history' | 'guide' | 'admin';
const inspirations = [ { name:'自然寫實', prompt:'一隻小狐狸坐在清晨的森林裡，柔和陽光穿過樹葉，自然攝影，細緻毛髮。', icon:'🌿' }, { name:'故事插畫', prompt:'一座漂浮在雲上的小小書店，溫暖燈光、奇幻故事插畫、豐富細節。', icon:'📚' }, { name:'產品設計', prompt:'一盞以海浪為靈感的桌燈，簡約產品攝影、淺色背景、柔和陰影。', icon:'💡' } ];
const fmt = (n:number) => new Intl.NumberFormat('zh-TW').format(n);
const statusLabel: Record<Job['status'],string> = { processing:'處理中',succeeded:'已完成',failed:'失敗・已退點',review:'待確認' };
export default function App() {
 const [data,setData] = useState<Dashboard>(()=>supabase ? {role:'student',classes:[],members:[],jobs:[],name:'同學'} : loadDemo());
 const [session,setSession] = useState(false);
 const [view,setView] = useState<View>('studio');
 const [kind,setKind] = useState<'image'|'video'>('image');
 const [classId,setClassId] = useState(new URLSearchParams(window.location.search).get('class') || sessionStorage.getItem('classroom-pending-class') || '');
 const [prompt,setPrompt] = useState('透明水母漂浮於深海，電影光影、細膩攝影。');
 const [ratio,setRatio] = useState('3:2');
 const [photo,setPhoto] = useState<string>('');
 const [photoName,setPhotoName] = useState('');
 const [busy,setBusy] = useState(false);
 const [result,setResult] = useState<{url:string;kind:'image'|'video'} | null>(null);
 const [notice,setNotice] = useState('');
 const [mobile,setMobile] = useState(false);
 const [mobileViewport,setMobileViewport] = useState(()=>window.matchMedia('(max-width: 760px)').matches);
 const [modal,setModal] = useState<'login'|'class'|'invite'|'quota'|null>(null);
 const [editing,setEditing] = useState<Member|null>(null);
 const [search,setSearch] = useState('');
 const [loadError,setLoadError] = useState('');
 const [joinCode,setJoinCode] = useState('');
 const [course,setCourse] = useState<{id:string;name:string}|null>(null);
 const [courseError,setCourseError] = useState('');
 const [loading,setLoading] = useState(false);
 const [saving,setSaving] = useState(false);
 const fileRef = useRef<HTMLInputElement>(null);
 const activeJob = useRef<string | null>(null);
 const pollTimer = useRef<ReturnType<typeof setTimeout>|null>(null);
 const alive = useRef(true);
 const refreshing = useRef(false);
 const current = data.classes.find(c=>c.id===classId) || data.classes[0];
 const me = data.members.find(m=>m.class_id===current?.id && (supabase ? m.user_id===data.viewer_id : m.id==='member-1'));
 const left = me ? Math.max(0,me.quota-me.used-me.reserved) : 0;
 const cost = current ? kind==='image'?current.image_cost:current.video_cost : 0;
 const admin = !supabase || data.role==='admin';
 async function refresh() {
  if(!supabase||refreshing.current)return;refreshing.current=true;setLoading(true);
  try {
   let next=await api<Dashboard>('dashboard');
   const target=classId;
   if(next.role==='student'&&target&&!next.classes.some(c=>c.id===target)){
    try{await api('join',{code:target});next=await api<Dashboard>('dashboard');setClassId(target);sessionStorage.removeItem('classroom-pending-class');setNotice('已加入班級，個人額度已設定。');}
    catch(e){setData(next);throw e;}
   }
   if(target&&next.classes.some(c=>c.id===target))sessionStorage.removeItem('classroom-pending-class');setData(next);setLoadError('');
  }catch(e){setLoadError((e as Error).message);}finally{refreshing.current=false;setLoading(false);}
 }
 useEffect(()=>{alive.current=true; if(!supabase)return ()=>{alive.current=false;}; supabase.auth.getSession().then(({data})=>{setSession(!!data.session);if(data.session)void refresh();}); const {data:sub}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(!!s);if(s)setTimeout(()=>void refresh(),0);}); return ()=>{alive.current=false;sub.subscription.unsubscribe();if(pollTimer.current)clearTimeout(pollTimer.current);};},[]);
 useEffect(()=>{if(!supabase)localStorage.setItem('classroom-studio-v2-demo',JSON.stringify(data));},[data]);
 useEffect(()=>{const mq=window.matchMedia('(max-width: 760px)');const update=()=>{setMobileViewport(mq.matches);if(!mq.matches)setMobile(false);};mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update);},[]);
 useEffect(()=>{if(!mobile)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setMobile(false);};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[mobile]);
 useEffect(()=>{if(!notice)return; const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
 useEffect(()=>{function prevent(e:BeforeUnloadEvent){if(result || busy){e.preventDefault();}} window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[result,busy]);
 useEffect(()=>{if(!modal)return;setNotice('');const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)setModal(null);};document.addEventListener('keydown',onKey);const el=document.querySelector<HTMLDialogElement>('dialog');el?.showModal();return()=>document.removeEventListener('keydown',onKey);},[modal,busy]);
 function navigate(v:View){setView(v);setMobile(false);}
 function switchKind(k:'image'|'video'){if(busy)return;setKind(k);setResult(null);}
 async function upload(file?:File){ if(!file)return; if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setNotice('請選擇 JPG、PNG 或 WebP 圖片。');return;} if(file.size>3*1024*1024){setNotice('照片需小於 3 MB，請縮小後再上傳。');return;} const reader=new FileReader();reader.onload=()=>{setPhoto(String(reader.result));setPhotoName(file.name);};reader.readAsDataURL(file); }
 async function login(){ if(!supabase){setModal(null);setNotice('目前為示範模式；正式 Google 登入需設定 Supabase。');return;} if(classId)sessionStorage.setItem('classroom-pending-class',classId);const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});if(error)setNotice(error.message); }
 async function signout(){if(busy){setNotice('請等任務完成後再登出。');return;}setResult(null);setPhoto('');if(supabase){await supabase.auth.signOut();setData({role:'student',classes:[],members:[],jobs:[],name:'同學'});}else setNotice('示範模式使用虛擬帳號，不會登出 Google。'); }
 async function poll(id:string){try{const response=await api<{status:Job['status'];url?:string;error?:string}>(`jobs?id=${id}`);if(!alive.current)return;if(response.status==='processing'){pollTimer.current=setTimeout(()=>void poll(id),5000);return;}setBusy(false);activeJob.current=null;if(response.url)setResult({kind,url:response.url});else setNotice(response.error || (response.status==='review'?'任務狀態需要老師確認，暫時保留預扣點數。':'影片未完成，點數已退回。'));void refresh();}catch{if(alive.current){setNotice('正在重新確認影片狀態，請保持頁面開啟。');pollTimer.current=setTimeout(()=>void poll(id),10000);}}}
 async function generate(){if(supabase&&!session){setModal('login');return;}if(!current){setNotice('請先加入班級。');return;}if(!prompt.trim()){setNotice('請先描述你想創作的內容。');return;}if(kind==='video'&&!photo){setNotice('請先選擇一張照片。');return;}if(left<cost){setNotice('剩餘點數不足，請聯絡老師調整額度。');return;}if(!current.active || new Date(current.expires_at).getTime()<Date.now()){setNotice('班級已暫停或課程已到期。');return;}setBusy(true);setResult(null);
 if(!supabase){await new Promise(r=>setTimeout(r,1200));setBusy(false);setNotice('示範已完成操作檢查；接上模型 API 後才會生成作品與扣點。');return;}
 try{const response=await api<{id:string;url?:string;status:Job['status']}>('generate',{classId:current.id,kind,prompt:prompt.trim(),ratio,image:kind==='video'?photo:undefined,requestId:crypto.randomUUID()});if(response.url){setResult({kind,url:response.url});setBusy(false);}else if(response.status==='processing'){activeJob.current=response.id;void poll(response.id);}else{setBusy(false);setNotice('任務待確認，請查看使用紀錄或聯絡老師。');}void refresh();}catch(e){setBusy(false);setNotice((e as Error).message);void refresh();}}
 async function download(){if(!result)return;try{const response=await fetch(result.url);if(!response.ok)throw new Error();const blob=await response.blob();const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=`classroom-${Date.now()}.${result.kind==='image'?'jpg':'mp4'}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch{window.open(result.url,'_blank','noopener,noreferrer');setNotice('作品已開啟，請使用瀏覽器另存檔案。');}}
 async function formAction(e:FormEvent<HTMLFormElement>){e.preventDefault();if(saving)return;setSaving(true);const f=new FormData(e.currentTarget);try{
 if(modal==='class'){const input={name:String(f.get('name')).trim(),description:String(f.get('description')).trim(),total:Number(f.get('total')),default_quota:Number(f.get('quota')),max_students:Number(f.get('capacity')),self_enrollment:true,image_cost:Number(f.get('imageCost')),video_cost:Number(f.get('videoCost')),expires_at:String(f.get('expires'))};if(input.default_quota>input.total)throw new Error('每人額度不可超過班級總點數。');if(supabase)await api('admin',{action:'create',...input});else{const c:Classroom={...input,id:crypto.randomUUID(),used:0,reserved:0,allocated:0,students:0,active:true};setData(d=>({...d,classes:[...d.classes,c]}));setClassId(c.id);}setNotice('班級已建立。');}
 if(modal==='invite'){const emails=String(f.get('emails')).split(/[\s,;]+/).map(v=>v.trim().toLowerCase()).filter(Boolean);if(emails.some(v=>!/^\S+@\S+\.\S+$/.test(v)))throw new Error('請確認 Email 格式。');if(supabase)await api('admin',{action:'invite',classId:current.id,emails});else{const unique=[...new Set(emails)].filter(v=>!data.members.some(m=>m.class_id===current.id&&m.email===v));if(current.allocated+unique.length*current.default_quota>current.total)throw new Error('未分配點數不足，請調整每人額度或班級總點數。');setData(d=>({...d,classes:d.classes.map(c=>c.id===current.id?{...c,students:c.students+unique.length,allocated:c.allocated+unique.length*c.default_quota}:c),members:[...d.members,...unique.map(email=>({id:crypto.randomUUID(),class_id:current.id,email,name:email.split('@')[0],quota:current.default_quota,used:0,reserved:0}))]}));}setNotice('學生名單已加入，名單內帳號可登入班級。');}
 if(modal==='quota'&&editing){const quota=Number(f.get('quota'));if(quota<editing.used+editing.reserved)throw new Error('額度不可低於已使用與預扣點數。');if(current.allocated+quota-editing.quota>current.total)throw new Error('班級未分配點數不足。');if(supabase)await api('admin',{action:'quota',classId:current.id,memberId:editing.id,quota});else setData(d=>({...d,classes:d.classes.map(c=>c.id===current.id?{...c,allocated:c.allocated+quota-editing.quota}:c),members:d.members.map(m=>m.id===editing.id?{...m,quota}:m)}));setNotice('個人額度已更新。');}
 setModal(null);if(supabase)void refresh();}catch(e){setNotice((e as Error).message);}finally{setSaving(false);}}
 async function toggleClass(){if(!current)return;if(supabase){try{await api('admin',{action:'toggle',classId:current.id,active:!current.active});void refresh();}catch(e){setNotice((e as Error).message);}}else setData(d=>({...d,classes:d.classes.map(c=>c.id===current.id?{...c,active:!c.active}:c)}));}
 async function enterCourse(e:FormEvent){e.preventDefault();if(saving)return;setSaving(true);setCourseError('');try{
  const selected=await api<{id:string;name:string}>('course',{code:joinCode.trim()});
  setCourse(selected);setClassId(selected.id);sessionStorage.setItem('classroom-pending-class',selected.id);
  if(session){await api('join',{code:selected.id});sessionStorage.removeItem('classroom-pending-class');setData(await api<Dashboard>('dashboard'));setLoadError('');setNotice('已加入班級。');}
 }catch(e){setCourseError((e as Error).message);setCourse(null);}finally{setSaving(false);}}
 async function copyInvite(){try{await navigator.clipboard.writeText(`網站：${window.location.origin}/\n課程代號：${current.course_code}`);setNotice('網站網址與課程代號已複製。');}catch{setNotice(`請分享網站網址與課程代號 ${current.course_code}。`);}}
 const courseForm=<form className="course-entry" onSubmit={e=>void enterCourse(e)}><label htmlFor="course-code">課程代號</label><div className="join-field"><input id="course-code" aria-label="課程代號" value={joinCode} onChange={e=>{setJoinCode(e.target.value.toUpperCase());setCourse(null);setClassId('');sessionStorage.removeItem('classroom-pending-class');setCourseError('');}} placeholder="例如 JOY015" autoComplete="off" autoCapitalize="characters" maxLength={8} required pattern="[A-Za-z0-9]{6,8}"/><button className="primary" disabled={saving}>{saving?'確認中…':'進入課程'}</button></div>{courseError&&<p className="course-error" role="alert">{courseError}</p>}</form>;
 const filteredJobs=data.jobs.filter(j=>j.class_id===current?.id);
 return <div className={`app-shell ${view==='studio'?'reference-layout':''}`}>
 {mobile&&<button className="mobile-backdrop" aria-label="關閉選單" onClick={()=>setMobile(false)}/>}
 <aside id="sidebar" className={`sidebar ${mobile?'is-open':''}`} inert={mobileViewport&&!mobile}>
  <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('studio');}}><span className="brand-mark"><GraduationCap size={23}/></span><span>Classroom<span className="brand-sub">STUDIO</span></span></a><button className="drawer-close icon-button" aria-label="關閉選單" onClick={()=>setMobile(false)}><X size={20}/></button>
  <div className="workspace-label">學習工作區 <span>01</span></div>
  <nav aria-label="主要導覽"><button className={view==='studio'?'active':''} onClick={()=>navigate('studio')}><WandSparkles size={19}/>創作工作室<span className="nav-new">NEW</span></button><button className={view==='history'?'active':''} onClick={()=>navigate('history')}><History size={19}/>使用紀錄</button><button className={view==='guide'?'active':''} onClick={()=>navigate('guide')}><BookOpen size={19}/>使用指南</button></nav>
  {admin&&<><div className="workspace-label second">教學管理</div><nav><button className={view==='admin'?'active':''} onClick={()=>navigate('admin')}><LayoutDashboard size={19}/>老師管理後台</button></nav></>}
  <div className="sidebar-bottom"><div className="privacy-card"><ShieldCheck size={22}/><strong>你的創作，由你保管</strong><p>本站不保存圖片與影片。<br/>完成後，記得下載作品。</p><button onClick={()=>navigate('guide')}>了解使用方式 <ChevronRight size={14}/></button></div><div className="sidebar-footer"><span>Classroom Studio</span><span>v1.0</span></div></div>
 </aside>
 <div className="main-shell" inert={mobileViewport&&mobile}>
  <header className="studio-header">
   <button className="studio-brand" onClick={()=>navigate('studio')}><img src="/logo.png" alt=""/><span>Classroom Studio</span></button>
   <div className="studio-tabs" role="tablist" aria-label="生成類型"><button role="tab" aria-selected={view==='studio'&&kind==='image'} onClick={()=>{navigate('studio');switchKind('image');}} disabled={busy}>圖片</button><button role="tab" aria-selected={view==='studio'&&kind==='video'} onClick={()=>{navigate('studio');switchKind('video');}} disabled={busy}>照片轉影片</button></div>
   <select className="studio-class" aria-label="目前班級" value={current?.id||''} disabled={busy} onChange={e=>{setClassId(e.target.value);setResult(null);}}>{data.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
   <span className="studio-balance">剩餘 {fmt(left)} 點</span>
   <details className="account-menu"><summary className="avatar" aria-label="帳號選單">{data.name.slice(0,1)}</summary><div><span>{data.name}</span><button onClick={()=>navigate('history')}>使用紀錄</button><button onClick={()=>navigate('guide')}>使用指南</button>{admin&&<button onClick={()=>navigate('admin')}>老師管理後台</button>}<button onClick={()=>session?void signout():setModal('login')}>{session?'登出':'Google 登入'}</button></div></details>
  </header>
  <main>
   {view!=='studio'&&!supabase&&<div className="demo-banner"><span><span className="demo-dot"/>目前為介面示範：可體驗班級管理與操作流程，不會呼叫模型或扣款。</span><button onClick={()=>{setData(structuredClone(demoData));setClassId('');setResult(null);setPrompt('');setPhoto('');setNotice('示範資料已重設。');}} aria-label="重設示範資料"><RotateCcw size={14}/></button></div>}
   {loadError&&<div className="error-banner">{loadError}<button onClick={()=>void refresh()}>重新載入</button></div>}
   {view!=='studio'&&<section className="page-heading"><div><div className="eyebrow">{view==='admin'?'TEACHER WORKSPACE':view==='history'?'YOUR ACTIVITY':view==='guide'?'GETTING STARTED':'YOUR CREATIVE SPACE'}</div><h1>{view==='admin'?'讓每份創意，都有公平的起點。':view==='history'?'每一次練習，都算數。':view==='guide'?'開始你的第一個創作。':'把想像，變成看得見的作品。'}</h1><p>{view==='admin'?'管理班級、分配額度，讓學生專心創作。':view==='history'?'查看生成狀態與點數使用；紀錄不包含照片與影片。':view==='guide'?'幾個簡單步驟，從靈感走到作品。':'用文字創作圖片，或讓一張照片開始說故事。'}</p></div>{view==='admin'?<button className="primary small" onClick={()=>setModal('class')} disabled={!!supabase&&!session}><Plus size={17}/>建立班級</button>:<span className="heading-art" aria-hidden="true"><Sparkles size={33}/></span>}</section>}
   {supabase&&!session?<div className="login-panel panel"><span className="big-icon"><GraduationCap size={32}/></span><h2>歡迎來到 AI 創作教室</h2><p>先輸入老師提供的課程代號，再使用 Google 帳號登入。</p>{courseForm}{(course||classId)&&<div className="course-confirm"><h3>{course?.name||'老師分享的課程'}</h3><button className="primary" onClick={()=>void login()}>使用 Google 帳號登入並加入</button></div>}<button className="teacher-login" onClick={()=>{sessionStorage.removeItem('classroom-pending-class');setClassId('');void supabase?.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}});}}>老師登入／已有班級的學生登入</button></div>:<>
   {view!=='studio'&&(!supabase||data.classes.length>0)&&<div className="class-strip"><div className="class-icon"><GraduationCap size={22}/></div><div className="class-select"><label htmlFor="class-select">目前班級</label><select id="class-select" value={current?.id||''} disabled={busy} onChange={e=>{setClassId(e.target.value);setResult(null);}}>{data.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><span className="class-status">{current?.active?'課程進行中':'班級已暫停'}</span><span className="class-expiry">課程期限 {current?.expires_at?.slice(0,10)}</span></div>}
   {loading&&<p className="loading-line"><LoaderCircle className="spin" size={16}/>更新班級資料中</p>}
   {!data.classes.length&&<div className="panel empty-class"><BookOpen size={32}/><h2>{admin?'建立你的第一個班級':'尚未加入班級'}</h2><p>{admin?'設定班級額度與名額，再分享網站網址與課程代號。':'輸入老師提供的課程代號，即可加入班級。'}</p>{admin?<button className="primary" onClick={()=>setModal('class')}><Plus size={17}/>建立班級</button>:courseForm}</div>}
   {view==='studio'&&current&&<div className="reference-studio">
    <section className="artwork" aria-label="本次作品預覽">
     <div className="artwork-toolbar"><span>{kind==='video'?'720p · 6 秒':ratio==='1:1'?'1024 × 1024':ratio==='3:2'?'1536 × 1024':'1024 × 1536'}<span className="preview-note">本次預覽</span></span>{result?<button className="download-button" onClick={()=>void download()}><Download size={21}/>下載{result.kind==='image'?'圖片':'影片'}</button>:<a className="download-button" href="/jellyfish.webp" download="classroom-studio-sample.webp"><Download size={21}/>下載圖片</a>}</div>
     <div className={`artwork-frame ${result?'has-result':''} ${kind==='video'&&photo?'has-photo':''}`} aria-busy={busy}>{result?(result.kind==='image'?<img src={result.url} alt="本次 AI 生成圖片"/>:<video src={result.url} controls playsInline/>):<picture>{!(kind==='video'&&photo)&&<source media="(max-width: 760px)" srcSet="/jellyfish-mobile.webp"/>}<img src={kind==='video'&&photo?photo:'/jellyfish.webp'} alt={kind==='video'&&photo?'準備轉為影片的照片':'透明水母漂浮於深海的示範作品'}/></picture>} {!result&&kind==='video'&&!photo&&<span className="video-hint">選擇照片，開始你的影片創作</span>}{busy&&<div className="artwork-loading" role="status"><LoaderCircle className="spin" size={30}/>正在創作中，請保持頁面開啟</div>}</div>
    </section>
    <section className="studio-controls" aria-label="生成設定">
     {kind==='video'&&<div className="reference-upload"><label htmlFor="source-photo">上傳照片</label><input id="source-photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} ref={fileRef} onChange={e=>void upload(e.target.files?.[0])}/><span>{photoName||'JPG、PNG、WebP，最大 3 MB'}</span>{photo&&<button className="secondary" disabled={busy} onClick={()=>{setPhoto('');setPhotoName('');}}>移除照片</button>}</div>}
     <div className="description-row"><label htmlFor="prompt">{kind==='image'?'畫面描述':'動作描述'}</label><textarea id="prompt" value={prompt} maxLength={2000} disabled={busy} onChange={e=>setPrompt(e.target.value)} rows={1} placeholder={kind==='image'?'描述你想創作的畫面':'例如：鏡頭緩慢靠近，水母輕輕游動。'}/></div>
     <div className="reference-settings"><fieldset><legend>{kind==='image'?'比例':'影片長度'}</legend>{kind==='image'?<div className="reference-ratios">{['1:1','3:2','2:3'].map(r=><button key={r} disabled={busy} aria-pressed={ratio===r} onClick={()=>setRatio(r)}>{r}</button>)}</div>:<span className="video-duration">6 秒</span>}</fieldset><div className="quality-field"><label htmlFor="quality">{kind==='image'?'品質':'輸出設定'}</label><select id="quality" disabled={busy}><option>{kind==='image'?'標準':'720p'}</option></select></div></div>
     <div className="usage-action"><div className="reference-usage"><div className="usage-heading"><strong>個人 AI 用量</strong><span>已用 {me?.used||0} / 上限 {me?.quota||0} 點</span></div><div className="usage-meter" role="meter" aria-label="個人已使用點數" aria-valuemin={0} aria-valuemax={me?.quota||100} aria-valuenow={me?.used||0}><span className="meter-used" style={{width:`${me?.quota?Math.min(100,me.used/me.quota*100):0}%`}}/><span className="meter-estimate" style={{width:`${me?.quota?Math.min(Math.max(0,me.quota-me.used),cost+me.reserved)/me.quota*100:0}%`}}/></div><div className="usage-legend"><span><i/>已使用 {me?.used||0} 點</span><span><i/>本次預估 {cost} 點</span></div></div><button className="generate-button" disabled={busy||!me||left<cost||!current.active} onClick={()=>void generate()}>{busy?<><LoaderCircle className="spin" size={22}/>正在創作中…</>:`生成${kind==='image'?'圖片':'影片'} · ${cost} 點`}</button></div>
     <p className="reference-footnote">本站不保存作品，請立即下載。</p>
     {!supabase&&<p className="reference-demo">示範模式：生成僅檢查操作流程，不呼叫模型、不扣點。上方為示範作品。</p>}
     {!me&&<p role="status">此帳號尚未有學生額度。老師可用學生帳號開啟班級連結測試加入。</p>}
    </section>
   </div>}
   {view==='history'&&current&&<div className="panel history-panel"><div className="section-header"><h2>點數使用紀錄</h2><span>{filteredJobs.length} 筆紀錄</span></div><div className="table-wrap"><table><thead><tr><th>創作類型</th><th>時間</th><th>狀態</th><th>使用點數</th></tr></thead><tbody>{filteredJobs.map(j=><tr key={j.id}><td><span className="table-kind">{j.kind==='image'?<ImagePlus size={17}/>:<Film size={17}/>} {j.kind==='image'?'圖片生成':'照片轉影片'}</span></td><td>{new Date(j.created_at).toLocaleString('zh-TW')}</td><td><span className={`status-pill ${j.status}`}>{statusLabel[j.status]}</span></td><td>{j.status==='failed'?'0':j.cost} 點</td></tr>)}</tbody></table>{!filteredJobs.length&&<p className="empty-table">尚未有生成紀錄，開始第一個作品吧。</p>}</div><p className="table-note"><ShieldCheck size={15}/>僅保留使用紀錄，不保存提示詞、照片或作品。</p></div>}
   {view==='admin'&&current&&<><div className="admin-stats">{[{label:'班級總點數',value:current.total,icon:Coins,caption:`已使用 ${fmt(current.used)} 點`},{label:'未分配點數',value:current.total-current.allocated,icon:ShieldCheck,caption:'可用於個別加點'},{label:'學生人數',value:current.students,icon:Users,caption:`預設每人 ${current.default_quota} 點`}].map(s=><div className="panel stat-card" key={s.label}><div><span>{s.label}</span><s.icon size={19}/></div><strong>{fmt(s.value)}<small>{s.label==='學生人數'?'人':'點'}</small></strong><p>{s.caption}</p></div>)}</div><div className="panel class-settings"><div><h2>班級設定</h2><p>圖片 {current.image_cost} 點／張 · 影片 {current.video_cost} 點／支 · 到期 {current.expires_at.slice(0,10)}</p><p className="course-code-display">課程代號：<strong>{current.course_code||'尚未設定'}</strong></p><p>{current.self_enrollment?`開放網址加入 · 名額 ${current.students} / ${current.max_students} 人`:'名單限定班級'}</p></div><div><button className="secondary" onClick={()=>void copyInvite()}><Mail size={16}/>複製網址與代號</button><button className="secondary" onClick={()=>void toggleClass()}>{current.active?'暫停班級':'恢復班級'}</button></div></div><div className="panel students-panel"><div className="section-header"><div><h2>學生與額度</h2><p>每位學生的額度獨立計算，不會被其他人用完。</p></div><button className="primary small" onClick={()=>setModal('invite')}><Plus size={16}/>加入學生</button></div><div className="search-field"><Search size={17}/><input placeholder="搜尋學生姓名或 Email" aria-label="搜尋學生" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>學生</th><th>個人額度</th><th>已使用</th><th>剩餘點數</th><th>管理</th></tr></thead><tbody>{data.members.filter(m=>m.class_id===current.id&&(m.email.includes(search)||m.name.includes(search))).map(m=><tr key={m.id}><td><div className="student-cell"><span className="avatar">{m.name.slice(0,1)}</span><div><strong>{m.name}</strong><small>{m.email}</small></div></div></td><td>{m.quota} 點</td><td>{m.used} 點</td><td><strong>{m.quota-m.used-m.reserved} 點</strong></td><td><button className="text-button" onClick={()=>{setEditing(m);setModal('quota');}}>調整額度</button></td></tr>)}</tbody></table>{!data.members.filter(m=>m.class_id===current.id).length&&<p className="empty-table">尚未有學生加入。分享網站網址與課程代號，學生登入後會自動出現在這裡。</p>}</div>{!supabase&&current.id==='design-101'&&<p className="table-note">示範僅顯示 3 位學生；班級統計為 30 人的範例資料。</p>}</div>{data.jobs.some(j=>j.status==='review')&&<div className="panel review-panel"><h2>待確認任務</h2><p>模型連線中斷的任務會保留點數，請先查證供應商是否收費或完成，再決定扣點或退款。</p>{data.jobs.filter(j=>j.status==='review'&&j.class_id===current.id).map(j=><div key={j.id}><span>{j.id} · {j.cost} 點</span>{(['success','refund'] as const).map(a=><button className="secondary" key={a} onClick={async()=>{try{await api('admin',{action:'resolve',jobId:j.id,resolution:a});await refresh();}catch(e){setNotice((e as Error).message);}}}>{a==='success'?'確認完成扣點':'確認失敗退款'}</button>)}</div>)}</div>}</>}
   {view==='guide'&&<div className="guide-grid">{[{number:'01',title:'用課程帳號登入',text:'開啟老師分享的班級連結，使用 Google 帳號登入後自動加入。每個班級有獨立的個人額度。',icon:GraduationCap},{number:'02',title:'選擇創作方式',text:'圖片生成：輸入畫面描述。照片轉影片：選擇照片並描述動作。',icon:WandSparkles},{number:'03',title:'確認點數後生成',text:'生成前會顯示使用點數。每次最多一個任務，確認失敗後退回預扣點數。',icon:Coins},{number:'04',title:'立即下載你的作品',text:'本站不建立作品庫。圖片離開頁面後無法取回，影片下載連結也有有效期限。',icon:Download}].map(g=><div className="panel guide-card" key={g.number}><span className="guide-number">{g.number}</span><g.icon size={25}/><h2>{g.title}</h2><p>{g.text}</p></div>)}<div className="panel guide-policy"><ShieldCheck size={25}/><div><h2>關於照片與作品</h2><p>照片只在本次操作中暫時處理，不上傳至本站的檔案儲存空間。生成內容會交由 OpenAI 或 xAI 處理，適用各供應商的資料政策。請使用你有權使用的照片。</p><p>網站保留班級、點數與任務狀態，以便管理額度。關閉網頁不會取消已提交的影片任務。</p></div></div></div>}
   </>}
   {view!=='studio'&&<footer className="page-footer"><span>Classroom Studio <span className="footer-dot">·</span> 每個想像，都值得一次練習。</span><button onClick={()=>navigate('guide')}>使用說明 <ArrowUpRight size={13}/></button></footer>}
  </main>
 </div>
 {notice&&!modal&&<div className="toast" role="status"><CircleAlert size={19}/><span>{notice}</span><button aria-label="關閉通知" onClick={()=>setNotice('')}><X size={17}/></button></div>}
 {modal&&<dialog className="modal" onCancel={()=>setModal(null)}><div className="modal-heading"><h2>{modal==='login'?'登入創作教室':modal==='class'?'建立新班級':modal==='invite'?'加入學生名單':'調整個人額度'}</h2><button className="icon-button" aria-label="關閉視窗" onClick={()=>setModal(null)}><X size={20}/></button></div>{notice&&<div className="modal-notice" role="alert">{notice}</div>}{modal==='login'?<div className="login-modal"><span className="big-icon"><GraduationCap size={34}/></span><p>使用 Google 帳號登入，加入老師開放的課程。</p><button className="primary" onClick={()=>void login()}>使用 Google 帳號登入</button><small>你的額度會綁定帳號，換裝置也能繼續使用。</small></div>:<form onSubmit={e=>void formAction(e)}>{modal==='class'&&<><label>班級名稱<input name="name" required maxLength={80} placeholder="例如：AI 視覺創作入門"/></label><label>課程說明<input name="description" maxLength={160} placeholder="簡短描述這堂課"/></label><div className="form-grid"><label>班級總點數<input name="total" type="number" min="1" max="1000000" defaultValue="3000" required/></label><label>班級人數上限<input name="capacity" type="number" min="1" max="200" defaultValue="15" required/></label><label>每人預設額度<input name="quota" type="number" min="1" max="100000" defaultValue="90" required/></label><label>圖片扣點／張<input name="imageCost" type="number" min="1" max="10000" defaultValue="5" required/></label><label>影片扣點／支<input name="videoCost" type="number" min="1" max="10000" defaultValue="20" required/></label></div><label>課程到期日<input name="expires" type="date" min={new Date().toISOString().slice(0,10)} defaultValue="2026-12-31" required/></label><p className="form-help">學生輸入課程代號後用 Google 登入，自動加入。名額與可分配點數不足時會停止加入。點數是課程自訂單位，請依 API 成本設定。</p></>}{modal==='invite'&&<><p>這是選用的名單匯入；也可以直接分享網站網址與課程代號讓學生自行加入。每位學生預設 {current.default_quota} 點。</p><label>學生 Email<textarea name="emails" required rows={6} placeholder={'student1@gmail.com\nstudent2@gmail.com'}/></label><p className="form-help">每行一個 Email，也可以用逗號分隔。重複帳號不會再次領取額度。</p></>}{modal==='quota'&&editing&&<><p>{editing.name} · {editing.email}</p><label>個人總額度<input name="quota" type="number" min={editing.used+editing.reserved} max="100000" defaultValue={editing.quota} required/></label><p className="form-help">已使用 {editing.used} 點，預扣 {editing.reserved} 點。新增額度從班級未分配點數支出。</p></>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(null)}>取消</button><button type="submit" className="primary" disabled={saving}>{modal==='class'?'建立班級':modal==='invite'?'加入名單':'儲存額度'}</button></div></form>}</dialog>}
 </div>;
}
